{% set name = "google-cloud-audit-log" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google_cloud_audit_log-{{ version }}.tar.gz
  sha256: 901428b257020d8c1d1133e0fa004164a555e5a395c7ca3cdbb8486513df3a65

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
    - googleapis-common-protos >=1.56.2,<2.0dev

test:
  imports:
    - google.cloud.audit.audit_log_pb2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-audit-log
  summary: Google Cloud Audit Protos
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/googleapis/python-audit-log
  dev_url: https://github.com/googleapis/python-audit-log

extra:
  recipe-maintainers:
    - xylar
